# Generated by Django 6.0.1 on 2026-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnsentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, help_text='Optional: Leave blank for anonymous', max_length=100, null=True)),
                ('receiver_name', models.CharField(help_text='Required: Who this message is for', max_length=100)),
                ('message_content', models.TextField(help_text='Your unsent message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
