# Generated by Django 6.0.1 on 2026-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsentmessage',
            name='music_file',
            field=models.FileField(blank=True, help_text='Optional: Attach a music file (MP3, WAV, etc.)', null=True, upload_to='messages_music/'),
        ),
    ]
