# Generated by Django 6.0.1 on 2026-01-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_unsentmessage_music_file'),
    ]

    operations = [
    ]
