# Generated by Django 6.0.1 on 2026-01-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_add_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsentmessage',
            name='preset_music',
            field=models.CharField(blank=True, help_text='Optional: Select from preset music collection', max_length=255, null=True),
        ),
    ]
