# Generated by Django 6.0.1 on 2026-01-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_add_preset_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsentmessage',
            name='voicemail',
            field=models.FileField(blank=True, help_text='Optional: Voice message recording', null=True, upload_to='voicemails/'),
        ),
    ]
