# Generated by Django on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_add_voicemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsentmessage',
            name='image_file',
            field=models.FileField(blank=True, help_text='Optional: Photo captured from camera', null=True, upload_to='messages_media/images/'),
        ),
        migrations.AddField(
            model_name='unsentmessage',
            name='video_clip',
            field=models.FileField(blank=True, help_text='Optional: Short video clip (max ~15s)', null=True, upload_to='messages_media/videos/'),
        ),
    ]
