# Generated by Django on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_add_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsentmessage',
            name='ghost_draft',
            field=models.TextField(blank=True, help_text='Deleted/overwritten text from drafting', null=True),
        ),
    ]
